#!/usr/bin/env bash

DOT_VIM="https://github.com/dansomething/dot_vim.git"
CMDS="git vim"

# Check for necessary commands
for cmd in $CMDS; do
  hash $cmd >/dev/null 2>&1 || {
    echo "$cmd command not found. Please install $cmd."
    exit 1
  }
done

# Install Homeshick
if [ ! -s "$HOME/.homesick/repos/homeshick" ]; then
  echo "Installing Homeshick to manage dotfiles..."
  git clone git://github.com/andsens/homeshick.git $HOME/.homesick/repos/homeshick
fi

source "$HOME/.homesick/repos/homeshick/homeshick.sh"

# Install dot_vim files
homeshick clone $DOT_VIM
homeshick symlink dot_vim
