set nocompatible " be iMproved

" All of the plugins are installed with vim-plug from this file.
source ~/.vim/vim-plug.vim
" Platform (Windows, Mac, etc.) configuration.
source ~/.vim/platforms.vim
" All of the Vim configuration.
source ~/.vim/config.vim
" All hotkeys, not dependant on plugins, are mapped here.
source ~/.vim/mappings.vim
" Eclim-specific configuration.
source ~/.vim/eclim.vim
" Small custom functions.
source ~/.vim/functions.vim
" Auto commands.
source ~/.vim/autocmds.vim
" Attempt to speed up large file handling
source ~/.vim/largefiles.vim

" Extra local only config that is not committed
let extraFile=expand("~/.vim/extra.vim")
if filereadable(extraFile)
  exe "source" . extraFile
endif
